NutritionManagement/urls.py
from django.conf.urls import url
from . import views
app_name = 'NutritionManagement'
urlpatterns = [
    url(r'^breakfast/$',views.breakfast,name="breakfast"),
    url(r'^nutrientsInBreakfast',views.NutrientsCalc,name="NutrientsCalc"),
    url(r'^update/([0-9]+)/$', views.breakfast_edit, name="breakfast_edit"),
    url(r'^delete/([0-9]+)/$',views.breakfast_delete,name="breakfast_delete")
]

Shubham_WebTech/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from NutritionManagement import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^NutritionMangement/',include('NutritionManagement.urls')),
    url(r'^$',views.index,name="index"),
]

NutritionManagement/models.py
from django.db import models
import datetime
# Create your models here.

class Breakfast(models.Model):
    Item = models.CharField(max_length=250)
    quantity = models.FloatField()
    date = models.DateField(default=datetime.datetime.today())


    def __str__(self):
        return self.Item


class Nutrients(models.Model):
    item_name = models.CharField(max_length=200)
    protien = models.FloatField(blank=True,null=True)
    carbohydrates = models.FloatField(blank=True,null=True)
    fat = models.FloatField(blank=True,null=True)
    vitamin = models.FloatField(blank=True,null=True)
    mineral = models.FloatField(blank=True,null=True)
    calorie = models.FloatField()
    def __str__(self):
        return self.item_name

NutritionManagement/forms.py
from django.forms import ModelForm
from NutritionManagement.models import Breakfast

class BreakfastForm(ModelForm):
    class Meta:
        model = Breakfast
        exclude=['date']

NutritionManagement/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render
from .forms import BreakfastForm
from .models import Breakfast,Nutrients
import datetime
# Create your views here.


today_date = datetime.datetime.today()
def index(request):
    return render(request,'NutritionMangement/index.html')


def breakfast(request):


        if request.method == 'POST':
            break_form = BreakfastForm(request.POST)
            if break_form.is_valid():
                break_form.save(commit=True)
                # if break_form.cleaned_data['add']:
                #     break_form = BreakfastForm()
                #     return render(request, "NutritionMangement/breakfast.html", {"break_form": break_form})
                #print(break_form.cleaned_data['submit'])
                if 'submit' in request.POST:
                    return HttpResponseRedirect('/')
                else:
                    break_form = BreakfastForm()
                    eat_today = Breakfast.objects.filter(date=datetime.datetime.today().date())
                    print(eat_today)
                    return render(request, "NutritionMangement/breakfast.html",
                                  {"break_form": break_form, 'date': today_date, 'eat_today': eat_today})

            else:
                return HttpResponse("Not valid")


        else:
            break_form = BreakfastForm()
            eat_today = Breakfast.objects.filter(date=datetime.datetime.today().date())
            print(eat_today)
            return render(request,"NutritionMangement/breakfast.html",{"break_form":break_form,'date':today_date,'eat_today':eat_today})




def NutrientsCalc(request):
    eat_today= Breakfast.objects.filter(date=datetime.datetime.today().date())
    # nutrients = .objects.all()
    if eat_today :
        total_calorie = 0
        intake_today = []
        for item in eat_today:
            gain_today = Nutrients.objects.get(item_name=item.Item)
            gain_today.calorie = gain_today.calorie * item.quantity
            intake_today.append(gain_today)
            total_calorie = int(gain_today.calorie)+total_calorie
            print(gain_today)


        return render(request, 'NutritionMangement/Calories.html', {'intake_today': intake_today,'total_calorie':total_calorie})
    else:
        length = eat_today.count()
        break_form = BreakfastForm()
        print(length)
        return render(request,'NutritionMangement/breakfast.html',{'eat_nothing':length,"break_form":break_form,'date':today_date})



def breakfast_edit(request,item_id):
    edit_form = Breakfast.objects.get(id = item_id)
    if request.method == 'POST':
        edit_name = request.POST.get('name_item')
        edit_quantity = request.POST.get('quantity')
        if edit_name:
            edit_form.Item=edit_name
        else:
            edit_form.Item = edit_form.Item
        if edit_quantity:
            edit_form.quantity=edit_quantity
        else:
            edit_form.quantity = edit_form.quantity
        edit_form.save()
        break_form = BreakfastForm()
        eat_today = Breakfast.objects.filter(date=datetime.datetime.today().date())
        return render(request,"NutritionMangement/breakfast.html",{"break_form":break_form,'date':today_date,'eat_today':eat_today})



def breakfast_delete(request,item_id):

    try:
        edit_form = Breakfast.objects.get(id=item_id)
        if request.method == 'POST':
            edit_form.delete()
            break_form = BreakfastForm()
            eat_today = Breakfast.objects.filter(date=datetime.datetime.today().date())
            return render(request,"NutritionMangement/breakfast.html",{"break_form":break_form,'date':today_date,'eat_today':eat_today})

    except:
        break_form = BreakfastForm()
        eat_today = Breakfast.objects.filter(date=datetime.datetime.today().date())
        return render(request, "NutritionMangement/breakfast.html",
                      {"break_form": break_form, 'date': today_date, 'eat_today': eat_today})

templates/NutritionMangement/Calories.html
{% extends 'NutritionMangement/base.html' %}

{% block body_block %}
<div class="jumbotron">
<h2>Nutrients and Calorie intake </h2>
</div>

    <table class="table table-striped">
    <thead>
      <tr>
        <th>Item name</th>
          <th>Quantity</th>
        <th>Protein</th>
        <th>Vitamins</th>
          <th>Mineral</th>
          <th>Carbohydrates</th>
          <th>Fat</th>
          <th>Calorie</th>
      </tr>
    </thead>
    <tbody>

        {% for data in intake_today%}
             <tr>
            <td>{{ data.item_name }}</td>
             <td>{{ data.quantity  }}</td>
                 {% if data.protien %}
            <td>{{ data.protien }}</td>
                     {% else %}
                     <td>-</td>
                 {% endif %}
             {% if data.vitamin %}
             <td>{{ data.vitamin }}</td>
                 {% else %}
                 <td>-</td>
            {% endif %}
             {% if data.mineral %}
            <td>{{ data.mineral }}</td>
                     {% else %}
                     <td>-</td>
                 {% endif %}
             {% if data.carbohydrates %}
            <td>{{ data.carbohydrates }}</td>
                     {% else %}
                     <td>-</td>
                 {% endif %}
             {% if data.fat %}
            <td>{{ data.fat }}</td>
                     {% else %}
                     <td>-</td>
                 {% endif %}
             {% if data.calorie%}
            <td>{{ data.calorie}}</td>
                     {% else %}
                     <td>-</td>
                 {% endif %}




             </tr>

          {% endfor %}
    <td>
        Total Calorie :-- {{ total_calorie }}
    </td>



    </tbody>
  </table>

    <a href="{% url "NutritionManagement:breakfast" %}">Add another item</a>
{% endblock %}

templates/NutritionMangement/Dinner.html
{% extends 'NutritionMangement/base.html' %}
{% block title %}Breakfast{% endblock %}

{% block body_block %}
    {% load bootstrap3 %}
    <div class="jumbotron">
        <center>
            <h3>What you eat for breakfast today?</h3>
            {{ date.date }}
        </center>
    </div>
    <center>
    <form method="post" class="form-horizontal">
{% csrf_token %}
    {%  bootstrap_form break_form %}

    <input type="submit" class="btn btn-primary" name="submit" value="Save">
    <input class="btn btn-primary" type="submit"  name="SaveAnother" value="Save and Add another">
    </form>
</center>
    <h2 class="jumbotron">You added</h2>
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Item name</th>
        <th>Quantity</th>
          <th></th>
          <th></th>
      </tr>
    </thead>
    <tbody>
    <tr>
    {% for item in eat_today %}
        <td>{{ item.Item }}</td>
        <td>{{ item.quantity }}</td>
      <td><a class="btn btn-warning" data-toggle="modal"  id="{{ item.id }}" data-target="#edit">Edit</a> </td>
        <td><a class="btn btn-danger" data-toggle="modal"  id="{{ item.id }}" data-target="#delete">Delete</a> </td>
        <div class="modal fade" id="edit" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit</h4>
        </div>
        <div class="modal-body">
          <form method="post" action="{% url 'NutritionManagement:breakfast_edit' item.id %}">
              <input type="text" name="name_item" placeholder="{{ item.Item }}" />
              <input type="number" placeholder="{{ item.quantity }}" name="quantity"/>
              {% csrf_token %}
              <input type="submit" class="btn btn-warning" name="submit" value="Update">

          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
        <div class="modal fade" id="delete" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Are you sure to delete this Item</h4>
        </div>
        <div class="modal-body">

          <form method="post" action="{% url 'NutritionManagement:breakfast_delete' item.id %}">
              {% csrf_token %}
              <input type="submit" class="btn btn-danger" name="submit" value="Delete">

          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
      </tr>
    {% endfor %}
    </tbody>
  </table>

    <a class="btn btn-success" href="{% url 'NutritionManagement:NutrientsCalc' %}">Get calories</a>

    {% if eat_nothing == 0 %}
        <script>
            alert("First you have to eat something")
        </script>
    {% endif %}
{% endblock %}

templates/NutritionMangement/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Nutrition Mangement</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script
  src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
  crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Nutrition Advisor</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="{% url "NutritionManagement:breakfast" %}">Breakfast</a></li>
      <li><a href="#">Lunch</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
<div class="container">
    {% block body_block %}
    {% endblock %}
</div>


</body>
</html>

templates/NutritionMangement/breakfast.html
{% extends 'NutritionMangement/base.html' %}
{% block title %}Breakfast{% endblock %}

{% block body_block %}
    {% load bootstrap3 %}
    <div class="jumbotron">
        <center>
            <h3>What you eat for breakfast today?</h3>
            {{ date.date }}
        </center>
    </div>
    <center>
    <form method="post" class="form-horizontal">
{% csrf_token %}
    {%  bootstrap_form break_form %}

    <input type="submit" class="btn btn-primary" name="submit" value="Save">
    <input class="btn btn-primary" type="submit"  name="SaveAnother" value="Save and Add another">
    </form>
</center>
    <h2 class="jumbotron">You added</h2>
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Item name</th>
        <th>Quantity</th>
          <th></th>
          <th></th>
      </tr>
    </thead>
    <tbody>
    <tr>
    {% for item in eat_today %}
        <td>{{ item.Item }}</td>
        <td>{{ item.quantity }}</td>
      <td><a class="btn btn-warning" data-toggle="modal"  id="{{ item.id }}" data-target="#edit">Edit</a> </td>
        <td><a class="btn btn-danger" data-toggle="modal"  id="{{ item.id }}" data-target="#delete">Delete</a> </td>
        <div class="modal fade" id="edit" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit</h4>
        </div>
        <div class="modal-body">
          <form method="post" action="{% url 'NutritionManagement:breakfast_edit' item.id %}">
              <input type="text" name="name_item" placeholder="{{ item.Item }}" />
              <input type="number" placeholder="{{ item.quantity }}" name="quantity"/>
              {% csrf_token %}
              <input type="submit" class="btn btn-warning" name="submit" value="Update">

          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
        <div class="modal fade" id="delete" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Are you sure to delete this Item</h4>
        </div>
        <div class="modal-body">

          <form method="post" action="{% url 'NutritionManagement:breakfast_delete' item.id %}">
              {% csrf_token %}
              <input type="submit" class="btn btn-danger" name="submit" value="Delete">

          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
      </tr>
    {% endfor %}
    </tbody>
  </table>

    <a class="btn btn-success" href="{% url 'NutritionManagement:NutrientsCalc' %}">Get calories</a>

    {% if eat_nothing == 0 %}
        <script>
            alert("First you have to eat something")
        </script>
    {% endif %}
{% endblock %}

templates/NutritionMangement/edit_breakfast.html
{% extends 'NutritionMangement/base.html' %}

{% endblock %}

templates/NutritionMangement/index.html
{% extends "NutritionMangement/base.html" %}


{% block body_block %}
<div class="jumbotron">
    <h1>Welcome Shubham</h1>
</div>

{% endblock %}

templates/NutritionMangement/lunch.html
{% extends 'NutritionMangement/base.html' %}
{% block title %}Breakfast{% endblock %}

{% block body_block %}
    {% load bootstrap3 %}
    <div class="jumbotron">
        <center>
            <h3>What you eat for breakfast today?</h3>
            {{ date.date }}
        </center>
    </div>
    <center>
    <form method="post" class="form-horizontal">
{% csrf_token %}
    {%  bootstrap_form break_form %}

    <input type="submit" class="btn btn-primary" name="submit" value="Save">
    <input class="btn btn-primary" type="submit"  name="SaveAnother" value="Save and Add another">
    </form>
</center>
    <h2 class="jumbotron">You added</h2>
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Item name</th>
        <th>Quantity</th>
          <th></th>
          <th></th>
      </tr>
    </thead>
    <tbody>
    <tr>
    {% for item in eat_today %}
        <td>{{ item.Item }}</td>
        <td>{{ item.quantity }}</td>
      <td><a class="btn btn-warning" data-toggle="modal"  id="{{ item.id }}" data-target="#edit">Edit</a> </td>
        <td><a class="btn btn-danger" data-toggle="modal"  id="{{ item.id }}" data-target="#delete">Delete</a> </td>
        <div class="modal fade" id="edit" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit</h4>
        </div>
        <div class="modal-body">
          <form method="post" action="{% url 'NutritionManagement:breakfast_edit' item.id %}">
              <input type="text" name="name_item" placeholder="{{ item.Item }}" />
              <input type="number" placeholder="{{ item.quantity }}" name="quantity"/>
              {% csrf_token %}
              <input type="submit" class="btn btn-warning" name="submit" value="Update">

          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
        <div class="modal fade" id="delete" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Are you sure to delete this Item</h4>
        </div>
        <div class="modal-body">

          <form method="post" action="{% url 'NutritionManagement:breakfast_delete' item.id %}">
              {% csrf_token %}
              <input type="submit" class="btn btn-danger" name="submit" value="Delete">

          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
      </tr>
    {% endfor %}
    </tbody>
  </table>

    <a class="btn btn-success" href="{% url 'NutritionManagement:NutrientsCalc' %}">Get calories</a>

    {% if eat_nothing == 0 %}
        <script>
            alert("First you have to eat something")
        </script>
    {% endif %}
{% endblock %}